chore: wip

diff --git a/storage/framework/scripts/publish b/storage/framework/scripts/publish
--- a/storage/framework/scripts/publish
+++ b/storage/framework/scripts/publish
@@ -6,9 +6,6 @@ script_dir=$(realpath $(dirname "$0"))
 # Get all directories in the core path except for src/bun-create
 dirs=$(find "$script_dir/../core" -type d -maxdepth 1 -not -path "$script_dir/../bun-create")
 
-# Add the `core/components/stepper` directory to dirs, until we can release all ./components/*
-dirs="$dirs $script_dir/../core/components/stepper"
-
 # Check if no directories found
 if [ -z "$dirs" ]; then
   echo "No core packages found"
@@ -24,7 +21,7 @@ for dir in $dirs; do
   # Change to the directory
   cd $dir
 
-  bun publish --access public || echo "Failed to publish $dir"
+  bun publish --access public || echo "Failed to publish $dir" && exit 1
 
   # Check if the build command was successful
   if [ $? -ne 0 ]; then
